### ISSUE TITLE
wrapper.py not passing parent data to pyramid for add_object_url

### ISSUE THREAD

**Issue by adam-codeberg** [brandicted/nefertari#121]
Detailed discussion found here https://github.com/brandicted/ramses/issues/89#issuecomment-148740716

### Solution

wrapper.py failing to provide Pyramid with the right **kwarg key
See  https://github.com/brandicted/nefertari/blob/master/nefertari/wrappers.py#L312

It hits this part of Pyramid and dies https://github.com/Pylons/pyramid/blob/master/pyramid/url.py#L279 because it cant find the route based on the params given to it.
Pyramid needs a key:value in the **kwargs dict for the parent that its not being given.
Once I change the wrappers.py line to 

````python
resource.uid, **{'contacts_id': 1, resource.id_name: obj_pk})
````
It works, have confirmed with the postgresql database.

Next step is to find a way to assign the key:value programatically.

**Comment by adam-codeberg** [comment]
Have completed a programmatic solution, can be found in my fork here https://github.com/adam-codeberg/nefertari/blob/master/nefertari/wrappers.py#L290

**Comment by jstoiko** [comment]
Nice! Thanks for that @adam-codeberg can you create a PR?

**Comment by adam-codeberg** [comment]
You're welcome! I'll clean up that rogue print statement and create the PR in about ~8hrs once I'm back in the office.

**Comment by jstoiko** [comment]
This PR: https://github.com/brandicted/nefertari/pull/125 should fix both this issue and https://github.com/brandicted/ramses/issues/89.

@adam-codeberg: would you mind testing this PR?

**Comment by jstoiko** [comment]
Fixed. Finally got around to test this. Thanks!
